/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rev.projectuaspbol;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.border.LineBorder;




public class App extends javax.swing.JFrame {

    
    Color warna_utama = new Color(254,115,93);
    Color warna_default = new Color(184,207,229);
    CardLayout cardLogin,cardBody,cardContent;
    
    
    public App() {
        initComponents();
        this.setLocationRelativeTo(null);
      
        
        
        /*area login panel*/
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.setFocusPainted(false);
         
        nimField.setBorder(null);
        passwordField.setBorder(null);
        /*==================================*/
        
        /*area daftar panel*/
        daftarAlamatField.setBorder(new LineBorder(warna_default,2));
        daftarNamaField.setBorder(new LineBorder(warna_default,2));
        daftarNimField.setBorder(new LineBorder(warna_default,2));
        daftarPasswordField.setBorder(new LineBorder(warna_default,2));
        
        /*==================================*/
        
        cardLogin = (CardLayout)(login.getLayout());
        cardBody = (CardLayout) (app.getLayout());
        cardContent = (CardLayout) (content.getLayout());
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTipeMahasiswa = new javax.swing.ButtonGroup();
        app = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        logoLogin = new javax.swing.JLabel();
        nimPanelField = new javax.swing.JPanel();
        nimField = new javax.swing.JTextField();
        logoUser = new javax.swing.JLabel();
        passwordPanelField = new javax.swing.JPanel();
        passwordField = new javax.swing.JTextField();
        logoNim = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        panelDaftar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        alertNotif = new javax.swing.JLabel();
        daftaPanel = new javax.swing.JPanel();
        judul_panel_daftar = new javax.swing.JLabel();
        logoDaftar = new javax.swing.JLabel();
        daftarButton = new javax.swing.JButton();
        labelNamaField = new javax.swing.JLabel();
        daftarAlamatField = new javax.swing.JTextField();
        daftarNamaField = new javax.swing.JTextField();
        labelAlamatField = new javax.swing.JLabel();
        labelNimField = new javax.swing.JLabel();
        daftarNimField = new javax.swing.JTextField();
        labelPasswordField = new javax.swing.JLabel();
        daftarPasswordField = new javax.swing.JTextField();
        internalButon = new javax.swing.JRadioButton();
        externalButton = new javax.swing.JRadioButton();
        profesionalButton = new javax.swing.JRadioButton();
        body = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        logoNavbar = new javax.swing.JLabel();
        textMenuUtama = new javax.swing.JLabel();
        dashboardButton = new javax.swing.JLabel();
        kelaskuButton = new javax.swing.JLabel();
        pesertaButton = new javax.swing.JLabel();
        keuanganButton = new javax.swing.JLabel();
        textAkunSaya = new javax.swing.JLabel();
        editProfileButton = new javax.swing.JLabel();
        editProfileButton1 = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        dashboard2 = new javax.swing.JPanel();
        kelasku = new javax.swing.JPanel();
        kelasku2 = new javax.swing.JPanel();
        pesertaKelas = new javax.swing.JPanel();
        transaksi = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        app.setLayout(new java.awt.CardLayout());

        login.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        logoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-login-form.png"))); // NOI18N

        nimPanelField.setBackground(new java.awt.Color(254, 115, 93));

        nimField.setBackground(new java.awt.Color(254, 115, 93));
        nimField.setForeground(new java.awt.Color(255, 255, 255));
        nimField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimFieldActionPerformed(evt);
            }
        });

        logoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-nim-field.png"))); // NOI18N

        javax.swing.GroupLayout nimPanelFieldLayout = new javax.swing.GroupLayout(nimPanelField);
        nimPanelField.setLayout(nimPanelFieldLayout);
        nimPanelFieldLayout.setHorizontalGroup(
            nimPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nimPanelFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );
        nimPanelFieldLayout.setVerticalGroup(
            nimPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(nimField, javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nimPanelFieldLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoUser)
                .addContainerGap())
        );

        passwordPanelField.setBackground(new java.awt.Color(254, 115, 93));

        passwordField.setBackground(new java.awt.Color(254, 115, 93));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        logoNim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-password-field.png"))); // NOI18N

        javax.swing.GroupLayout passwordPanelFieldLayout = new javax.swing.GroupLayout(passwordPanelField);
        passwordPanelField.setLayout(passwordPanelFieldLayout);
        passwordPanelFieldLayout.setHorizontalGroup(
            passwordPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoNim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );
        passwordPanelFieldLayout.setVerticalGroup(
            passwordPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordField)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelFieldLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoNim)
                .addContainerGap())
        );

        loginButton.setBackground(new java.awt.Color(254, 115, 93));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        panelDaftar.setBackground(new java.awt.Color(254, 115, 93));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftarkan akun anda di aplikasi ini untuk mengambil ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NEW HERE ? ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("mata kuliah anda");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 115, 93));
        jLabel7.setText("DAFTAR");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelDaftarLayout = new javax.swing.GroupLayout(panelDaftar);
        panelDaftar.setLayout(panelDaftarLayout);
        panelDaftarLayout.setHorizontalGroup(
            panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
            .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(51, 51, 51)))
        );
        panelDaftarLayout.setVerticalGroup(
            panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDaftarLayout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(jLabel2)
                    .addContainerGap(375, Short.MAX_VALUE)))
        );

        alertNotif.setText("asdadasdasdsad");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(logoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nimPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(alertNotif)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(panelDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nimPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alertNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        login.add(loginPanel, "loginCard");

        daftaPanel.setBackground(new java.awt.Color(255, 255, 255));

        judul_panel_daftar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judul_panel_daftar.setForeground(new java.awt.Color(254, 115, 93));
        judul_panel_daftar.setText("DAFTAR AKUN");

        logoDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-daftar-form.png"))); // NOI18N

        daftarButton.setBackground(new java.awt.Color(254, 115, 93));
        daftarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        daftarButton.setForeground(new java.awt.Color(255, 255, 255));
        daftarButton.setText("DAFTAR");

        labelNamaField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNamaField.setForeground(new java.awt.Color(254, 115, 93));
        labelNamaField.setText("Nama Lengkap");

        daftarAlamatField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                daftarAlamatFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                daftarAlamatFieldFocusLost(evt);
            }
        });
        daftarAlamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarAlamatFieldActionPerformed(evt);
            }
        });

        daftarNamaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                daftarNamaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                daftarNamaFieldFocusLost(evt);
            }
        });
        daftarNamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarNamaFieldActionPerformed(evt);
            }
        });

        labelAlamatField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAlamatField.setForeground(new java.awt.Color(254, 115, 93));
        labelAlamatField.setText("Alamat");

        labelNimField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNimField.setForeground(new java.awt.Color(254, 115, 93));
        labelNimField.setText("Nim");

        daftarNimField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                daftarNimFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                daftarNimFieldFocusLost(evt);
            }
        });
        daftarNimField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarNimFieldActionPerformed(evt);
            }
        });

        labelPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPasswordField.setForeground(new java.awt.Color(254, 115, 93));
        labelPasswordField.setText("Password");

        daftarPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                daftarPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                daftarPasswordFieldFocusLost(evt);
            }
        });
        daftarPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarPasswordFieldActionPerformed(evt);
            }
        });

        groupTipeMahasiswa.add(internalButon);
        internalButon.setForeground(new java.awt.Color(254, 115, 93));
        internalButon.setText("External");
        internalButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internalButonActionPerformed(evt);
            }
        });

        groupTipeMahasiswa.add(externalButton);
        externalButton.setForeground(new java.awt.Color(254, 115, 93));
        externalButton.setText("Internal");
        externalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalButtonActionPerformed(evt);
            }
        });

        groupTipeMahasiswa.add(profesionalButton);
        profesionalButton.setForeground(new java.awt.Color(254, 115, 93));
        profesionalButton.setText("Profesional");
        profesionalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesionalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout daftaPanelLayout = new javax.swing.GroupLayout(daftaPanel);
        daftaPanel.setLayout(daftaPanelLayout);
        daftaPanelLayout.setHorizontalGroup(
            daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftaPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelNamaField)
                        .addComponent(daftarAlamatField, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addComponent(daftarNimField)
                        .addComponent(daftarPasswordField, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(labelPasswordField)
                    .addComponent(labelAlamatField)
                    .addComponent(labelNimField)
                    .addComponent(judul_panel_daftar)
                    .addGroup(daftaPanelLayout.createSequentialGroup()
                        .addComponent(externalButton)
                        .addGap(30, 30, 30)
                        .addComponent(internalButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profesionalButton))
                    .addComponent(daftarNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(160, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daftaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(daftarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        daftaPanelLayout.setVerticalGroup(
            daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftaPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(daftaPanelLayout.createSequentialGroup()
                        .addComponent(judul_panel_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(externalButton)
                            .addComponent(internalButon)
                            .addComponent(profesionalButton))
                        .addGap(25, 25, 25)
                        .addComponent(labelNamaField)
                        .addGap(18, 18, 18)
                        .addComponent(daftarNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(labelAlamatField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daftarAlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(labelNimField)
                        .addGap(4, 4, 4)
                        .addComponent(daftarNimField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPasswordField))
                    .addComponent(logoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(daftarPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daftarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        login.add(daftaPanel, "daftarCard");

        app.add(login, "card4");

        navbar.setBackground(new java.awt.Color(255, 255, 255));

        logoNavbar.setBackground(new java.awt.Color(255, 255, 255));
        logoNavbar.setFont(new java.awt.Font("Playfair Display", 0, 18)); // NOI18N
        logoNavbar.setForeground(new java.awt.Color(255, 153, 0));
        logoNavbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo Sadhar1.png"))); // NOI18N
        logoNavbar.setText("SIA USD");

        textMenuUtama.setBackground(new java.awt.Color(255, 255, 255));
        textMenuUtama.setFont(new java.awt.Font("Playfair Display", 0, 18)); // NOI18N
        textMenuUtama.setText("MENU UTAMA");

        dashboardButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        dashboardButton.setIcon(new javax.swing.ImageIcon("E:\\tugas tugas kuliah\\Semester 3\\New folder\\Last_Exam_PBOL\\src\\main\\resources\\logo-dashboard.png")); // NOI18N
        dashboardButton.setText("  Dashboard");

        kelaskuButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        kelaskuButton.setIcon(new javax.swing.ImageIcon("E:\\tugas tugas kuliah\\Semester 3\\New folder\\Last_Exam_PBOL\\src\\main\\resources\\logo-kelasku.png")); // NOI18N
        kelaskuButton.setText("     Kelasku");

        pesertaButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        pesertaButton.setIcon(new javax.swing.ImageIcon("E:\\tugas tugas kuliah\\Semester 3\\New folder\\Last_Exam_PBOL\\src\\main\\resources\\logo-peserta-kelas.png")); // NOI18N
        pesertaButton.setText("Peserta Kelas");

        keuanganButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        keuanganButton.setIcon(new javax.swing.ImageIcon("E:\\tugas tugas kuliah\\Semester 3\\New folder\\Last_Exam_PBOL\\src\\main\\resources\\logo-keuangan.png")); // NOI18N
        keuanganButton.setText("    Keuangan ");

        textAkunSaya.setBackground(new java.awt.Color(255, 255, 255));
        textAkunSaya.setFont(new java.awt.Font("Playfair Display", 0, 18)); // NOI18N
        textAkunSaya.setText("Akun Saya");

        editProfileButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        editProfileButton.setIcon(new javax.swing.ImageIcon("E:\\tugas tugas kuliah\\Semester 3\\New folder\\Last_Exam_PBOL\\src\\main\\resources\\logo-profile.png")); // NOI18N
        editProfileButton.setText("Edit Profile");

        editProfileButton1.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        editProfileButton1.setIcon(new javax.swing.ImageIcon("E:\\tugas tugas kuliah\\Semester 3\\New folder\\Last_Exam_PBOL\\src\\main\\resources\\logo-logout.png")); // NOI18N
        editProfileButton1.setText("    Log Out");

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textMenuUtama)
                    .addComponent(logoNavbar)
                    .addGroup(navbarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kelaskuButton)
                            .addComponent(dashboardButton)
                            .addComponent(pesertaButton)
                            .addComponent(keuanganButton)
                            .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(editProfileButton)
                                .addComponent(textAkunSaya)
                                .addComponent(editProfileButton1, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoNavbar)
                .addGap(18, 18, 18)
                .addComponent(textMenuUtama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dashboardButton)
                .addGap(18, 18, 18)
                .addComponent(kelaskuButton)
                .addGap(15, 15, 15)
                .addComponent(pesertaButton)
                .addGap(18, 18, 18)
                .addComponent(keuanganButton)
                .addGap(33, 33, 33)
                .addComponent(textAkunSaya)
                .addGap(18, 18, 18)
                .addComponent(editProfileButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editProfileButton1)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(204, 255, 51));
        content.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(246, 253, 255));

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        content.add(dashboard, "dashboardCard");

        javax.swing.GroupLayout dashboard2Layout = new javax.swing.GroupLayout(dashboard2);
        dashboard2.setLayout(dashboard2Layout);
        dashboard2Layout.setHorizontalGroup(
            dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        dashboard2Layout.setVerticalGroup(
            dashboard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        content.add(dashboard2, "card3");

        javax.swing.GroupLayout kelaskuLayout = new javax.swing.GroupLayout(kelasku);
        kelasku.setLayout(kelaskuLayout);
        kelaskuLayout.setHorizontalGroup(
            kelaskuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        kelaskuLayout.setVerticalGroup(
            kelaskuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        content.add(kelasku, "card4");

        javax.swing.GroupLayout kelasku2Layout = new javax.swing.GroupLayout(kelasku2);
        kelasku2.setLayout(kelasku2Layout);
        kelasku2Layout.setHorizontalGroup(
            kelasku2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        kelasku2Layout.setVerticalGroup(
            kelasku2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        content.add(kelasku2, "card5");

        javax.swing.GroupLayout pesertaKelasLayout = new javax.swing.GroupLayout(pesertaKelas);
        pesertaKelas.setLayout(pesertaKelasLayout);
        pesertaKelasLayout.setHorizontalGroup(
            pesertaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        pesertaKelasLayout.setVerticalGroup(
            pesertaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        content.add(pesertaKelas, "card6");

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 836, Short.MAX_VALUE)
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
        );

        content.add(transaksi, "card7");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        app.add(body, "mainMenu");

        getContentPane().add(app, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nimFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
      cardLogin.show(login, "daftarCard");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void daftarNimFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarNimFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarNimFieldActionPerformed

    private void daftarNamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarNamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarNamaFieldActionPerformed

    private void daftarAlamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarAlamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarAlamatFieldActionPerformed

    private void daftar_nama_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void daftarAlamatFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarAlamatFieldFocusGained
        Color warna_utama = new Color(254,115,93);
        daftarAlamatField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_daftarAlamatFieldFocusGained

    private void daftarAlamatFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarAlamatFieldFocusLost
        Color warna_default = new Color(184,207,229);
        daftarAlamatField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_daftarAlamatFieldFocusLost

    private void daftarPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarPasswordFieldActionPerformed

    private void internalButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internalButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internalButonActionPerformed

    private void externalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_externalButtonActionPerformed

    private void profesionalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesionalButtonActionPerformed

    private void daftarNamaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarNamaFieldFocusGained

          daftarNamaField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_daftarNamaFieldFocusGained

    private void daftarNamaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarNamaFieldFocusLost

        daftarNamaField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_daftarNamaFieldFocusLost

    private void daftarNimFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarNimFieldFocusGained
        
        daftarNimField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_daftarNimFieldFocusGained

    private void daftarPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarPasswordFieldFocusGained
         daftarPasswordField.setBorder(new LineBorder(warna_utama,2));
       
    }//GEN-LAST:event_daftarPasswordFieldFocusGained

    private void daftarNimFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarNimFieldFocusLost
        daftarNimField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_daftarNimFieldFocusLost

    private void daftarPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarPasswordFieldFocusLost
        daftarPasswordField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_daftarPasswordFieldFocusLost

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if (nimField.getText().equals("") && passwordField.getText().equals("")) {
            alertNotif.setForeground(Color.red);
        } else {
            alertNotif.setForeground(Color.blue);
            cardBody.show(app, "mainMenu");
            cardContent.show(content, "dashboardContent");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertNotif;
    private javax.swing.JPanel app;
    private javax.swing.JPanel body;
    private javax.swing.JPanel content;
    private javax.swing.JPanel daftaPanel;
    private javax.swing.JTextField daftarAlamatField;
    private javax.swing.JButton daftarButton;
    private javax.swing.JTextField daftarNamaField;
    private javax.swing.JTextField daftarNimField;
    private javax.swing.JTextField daftarPasswordField;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dashboard2;
    private javax.swing.JLabel dashboardButton;
    private javax.swing.JLabel editProfileButton;
    private javax.swing.JLabel editProfileButton1;
    private javax.swing.JRadioButton externalButton;
    private javax.swing.ButtonGroup groupTipeMahasiswa;
    private javax.swing.JRadioButton internalButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judul_panel_daftar;
    private javax.swing.JPanel kelasku;
    private javax.swing.JPanel kelasku2;
    private javax.swing.JLabel kelaskuButton;
    private javax.swing.JLabel keuanganButton;
    private javax.swing.JLabel labelAlamatField;
    private javax.swing.JLabel labelNamaField;
    private javax.swing.JLabel labelNimField;
    private javax.swing.JLabel labelPasswordField;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoDaftar;
    private javax.swing.JLabel logoLogin;
    private javax.swing.JLabel logoNavbar;
    private javax.swing.JLabel logoNim;
    private javax.swing.JLabel logoUser;
    private javax.swing.JPanel navbar;
    private javax.swing.JTextField nimField;
    private javax.swing.JPanel nimPanelField;
    private javax.swing.JPanel panelDaftar;
    private javax.swing.JTextField passwordField;
    private javax.swing.JPanel passwordPanelField;
    private javax.swing.JLabel pesertaButton;
    private javax.swing.JPanel pesertaKelas;
    private javax.swing.JRadioButton profesionalButton;
    private javax.swing.JLabel textAkunSaya;
    private javax.swing.JLabel textMenuUtama;
    private javax.swing.JPanel transaksi;
    // End of variables declaration//GEN-END:variables
}
