/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rev.projectuaspbol;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.border.LineBorder;




public class App extends javax.swing.JFrame {

    
    Color warna_utama = new Color(254,115,93); //warna orange muda
    Color warna_default = new Color(184,207,229);// warna biru ke abu-abuan
    CardLayout cardLogin,cardBody,cardContent;
    
    
    public App() {
        initComponents();
        this.setLocationRelativeTo(null);
      
        
        
        /*area login panel*/
        loginButton.setBorder(null);
        loginButton.setBorderPainted(false);
        loginButton.setFocusPainted(false);
         
        nimField.setBorder(null);
        passwordField.setBorder(null);
        /*==================================*/
        
        /*area daftar panel*/
        daftarAlamatField.setBorder(new LineBorder(warna_default,2));
        daftarNamaField.setBorder(new LineBorder(warna_default,2));
        daftarNimField.setBorder(new LineBorder(warna_default,2));
        daftarPasswordField.setBorder(new LineBorder(warna_default,2));
        
        /*==================================*/
        
         /*area edit profile panel*/
        ubahNamaField.setBorder(new LineBorder(warna_default,2));
        ubahAlamatField.setBorder(new LineBorder(warna_default,2));
        ubahNimField.setBorder(new LineBorder(warna_default,2));
        ubahPasswordField.setBorder(new LineBorder(warna_default,2));
        /*==================================*/
        
        
        cardLogin = (CardLayout)(login.getLayout());
        cardBody = (CardLayout) (app.getLayout());
        cardContent = (CardLayout) (content.getLayout());
        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupTipeMahasiswa = new javax.swing.ButtonGroup();
        app = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        loginPanel = new javax.swing.JPanel();
        logoLogin = new javax.swing.JLabel();
        nimPanelField = new javax.swing.JPanel();
        nimField = new javax.swing.JTextField();
        logoUser = new javax.swing.JLabel();
        passwordPanelField = new javax.swing.JPanel();
        passwordField = new javax.swing.JTextField();
        logoNim = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        panelDaftar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        alertNotif = new javax.swing.JLabel();
        daftaPanel = new javax.swing.JPanel();
        judul_panel_daftar = new javax.swing.JLabel();
        logoDaftar = new javax.swing.JLabel();
        daftarButton = new javax.swing.JButton();
        labelNamaField = new javax.swing.JLabel();
        daftarNamaField = new javax.swing.JTextField();
        labelAlamatField = new javax.swing.JLabel();
        daftarAlamatField = new javax.swing.JTextField();
        labelNimField = new javax.swing.JLabel();
        daftarNimField = new javax.swing.JTextField();
        labelPasswordField = new javax.swing.JLabel();
        daftarPasswordField = new javax.swing.JTextField();
        internalButon = new javax.swing.JRadioButton();
        externalButton = new javax.swing.JRadioButton();
        profesionalButton = new javax.swing.JRadioButton();
        body = new javax.swing.JPanel();
        navbar = new javax.swing.JPanel();
        logoNavbar = new javax.swing.JLabel();
        textMenuUtama = new javax.swing.JLabel();
        dashboardButton = new javax.swing.JLabel();
        kelaskuButton = new javax.swing.JLabel();
        pesertaButton = new javax.swing.JLabel();
        keuanganButton = new javax.swing.JLabel();
        textAkunSaya = new javax.swing.JLabel();
        editProfileButton = new javax.swing.JLabel();
        logOutButton = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        dashboard = new javax.swing.JPanel();
        selamatDatangPanel = new javax.swing.JPanel();
        logoSelamatDatang = new javax.swing.JLabel();
        textSelamatDatang = new javax.swing.JLabel();
        namaPeserta = new javax.swing.JLabel();
        textTambahan1 = new javax.swing.JLabel();
        textTambahan2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        dashboardAktif = new javax.swing.JPanel();
        selamatDatangPanel2 = new javax.swing.JPanel();
        logoSelamatDatang1 = new javax.swing.JLabel();
        textSelamatDatang1 = new javax.swing.JLabel();
        namaPeserta1 = new javax.swing.JLabel();
        textTambahan3 = new javax.swing.JLabel();
        textTambahan4 = new javax.swing.JLabel();
        kelasku = new javax.swing.JPanel();
        textKelasku = new javax.swing.JLabel();
        textMataKuliah1 = new javax.swing.JLabel();
        mataKuliahPilihan1 = new javax.swing.JComboBox<>();
        textMataKuliah2 = new javax.swing.JLabel();
        mataKuliahPilihan2 = new javax.swing.JComboBox<>();
        textMatakuliah3 = new javax.swing.JLabel();
        mataKuliahPilihan3 = new javax.swing.JComboBox<>();
        logoPanelKelasku = new javax.swing.JLabel();
        tambahMatkulButton = new javax.swing.JButton();
        kelaskuAktif = new javax.swing.JPanel();
        pesertaKelas = new javax.swing.JPanel();
        labelMataKuliah1 = new javax.swing.JLabel();
        mataKuliah1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelPesertaMatkul1 = new javax.swing.JTable();
        labelMataKuliah2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelPesertaMatkul2 = new javax.swing.JTable();
        labelMataKuliah3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelPesertaMatkul3 = new javax.swing.JTable();
        mataKuliah2 = new javax.swing.JLabel();
        mataKuliah3 = new javax.swing.JLabel();
        transaksi = new javax.swing.JPanel();
        panelInfoPeserta = new javax.swing.JPanel();
        logoSelamatDatang2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        bayarButton = new javax.swing.JButton();
        editProfile = new javax.swing.JPanel();
        logoEditProfile = new javax.swing.JLabel();
        labelNamaField1 = new javax.swing.JLabel();
        ubahNamaField = new javax.swing.JTextField();
        labelAlamatField1 = new javax.swing.JLabel();
        ubahAlamatField = new javax.swing.JTextField();
        labelNimField1 = new javax.swing.JLabel();
        ubahNimField = new javax.swing.JTextField();
        labelPasswordField1 = new javax.swing.JLabel();
        ubahPasswordField = new javax.swing.JTextField();
        ubahButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        app.setLayout(new java.awt.CardLayout());

        login.setLayout(new java.awt.CardLayout());

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        logoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-login-form.png"))); // NOI18N

        nimPanelField.setBackground(new java.awt.Color(254, 115, 93));

        nimField.setBackground(new java.awt.Color(254, 115, 93));
        nimField.setForeground(new java.awt.Color(255, 255, 255));
        nimField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimFieldActionPerformed(evt);
            }
        });

        logoUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-nim-field.png"))); // NOI18N

        javax.swing.GroupLayout nimPanelFieldLayout = new javax.swing.GroupLayout(nimPanelField);
        nimPanelField.setLayout(nimPanelFieldLayout);
        nimPanelFieldLayout.setHorizontalGroup(
            nimPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nimPanelFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );
        nimPanelFieldLayout.setVerticalGroup(
            nimPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(nimField, javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nimPanelFieldLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoUser)
                .addContainerGap())
        );

        passwordPanelField.setBackground(new java.awt.Color(254, 115, 93));

        passwordField.setBackground(new java.awt.Color(254, 115, 93));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        logoNim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon-password-field.png"))); // NOI18N

        javax.swing.GroupLayout passwordPanelFieldLayout = new javax.swing.GroupLayout(passwordPanelField);
        passwordPanelField.setLayout(passwordPanelFieldLayout);
        passwordPanelFieldLayout.setHorizontalGroup(
            passwordPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelFieldLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoNim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
        );
        passwordPanelFieldLayout.setVerticalGroup(
            passwordPanelFieldLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(passwordField)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, passwordPanelFieldLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoNim)
                .addContainerGap())
        );

        loginButton.setBackground(new java.awt.Color(254, 115, 93));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        panelDaftar.setBackground(new java.awt.Color(254, 115, 93));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftarkan akun anda di aplikasi ini untuk mengambil ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NEW HERE ? ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("mata kuliah anda");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 115, 93));
        jLabel7.setText("DAFTAR");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout panelDaftarLayout = new javax.swing.GroupLayout(panelDaftar);
        panelDaftar.setLayout(panelDaftarLayout);
        panelDaftarLayout.setHorizontalGroup(
            panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
            .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDaftarLayout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(51, 51, 51)))
        );
        panelDaftarLayout.setVerticalGroup(
            panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDaftarLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDaftarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelDaftarLayout.createSequentialGroup()
                    .addGap(177, 177, 177)
                    .addComponent(jLabel2)
                    .addContainerGap(375, Short.MAX_VALUE)))
        );

        alertNotif.setText("NIM / PASSWORD ANDA SALAH");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(logoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nimPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(alertNotif)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(panelDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDaftar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logoLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nimPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alertNotif, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        login.add(loginPanel, "loginCard");

        daftaPanel.setBackground(new java.awt.Color(255, 255, 255));

        judul_panel_daftar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        judul_panel_daftar.setForeground(new java.awt.Color(254, 115, 93));
        judul_panel_daftar.setText("DAFTAR AKUN");

        logoDaftar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-daftar-form.png"))); // NOI18N

        daftarButton.setBackground(new java.awt.Color(254, 115, 93));
        daftarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        daftarButton.setForeground(new java.awt.Color(255, 255, 255));
        daftarButton.setText("DAFTAR");

        labelNamaField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNamaField.setForeground(new java.awt.Color(254, 115, 93));
        labelNamaField.setText("Nama Lengkap");

        daftarNamaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                daftarNamaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                daftarNamaFieldFocusLost(evt);
            }
        });
        daftarNamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarNamaFieldActionPerformed(evt);
            }
        });

        labelAlamatField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAlamatField.setForeground(new java.awt.Color(254, 115, 93));
        labelAlamatField.setText("Alamat");

        daftarAlamatField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                daftarAlamatFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                daftarAlamatFieldFocusLost(evt);
            }
        });
        daftarAlamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarAlamatFieldActionPerformed(evt);
            }
        });

        labelNimField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNimField.setForeground(new java.awt.Color(254, 115, 93));
        labelNimField.setText("Nim");

        daftarNimField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                daftarNimFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                daftarNimFieldFocusLost(evt);
            }
        });
        daftarNimField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarNimFieldActionPerformed(evt);
            }
        });

        labelPasswordField.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPasswordField.setForeground(new java.awt.Color(254, 115, 93));
        labelPasswordField.setText("Password");

        daftarPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                daftarPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                daftarPasswordFieldFocusLost(evt);
            }
        });
        daftarPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarPasswordFieldActionPerformed(evt);
            }
        });

        groupTipeMahasiswa.add(internalButon);
        internalButon.setForeground(new java.awt.Color(254, 115, 93));
        internalButon.setText("External");
        internalButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                internalButonActionPerformed(evt);
            }
        });

        groupTipeMahasiswa.add(externalButton);
        externalButton.setForeground(new java.awt.Color(254, 115, 93));
        externalButton.setText("Internal");
        externalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                externalButtonActionPerformed(evt);
            }
        });

        groupTipeMahasiswa.add(profesionalButton);
        profesionalButton.setForeground(new java.awt.Color(254, 115, 93));
        profesionalButton.setText("Profesional");
        profesionalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesionalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout daftaPanelLayout = new javax.swing.GroupLayout(daftaPanel);
        daftaPanel.setLayout(daftaPanelLayout);
        daftaPanelLayout.setHorizontalGroup(
            daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftaPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelNamaField)
                        .addComponent(daftarAlamatField, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                        .addComponent(daftarNimField)
                        .addComponent(daftarPasswordField, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(labelPasswordField)
                    .addComponent(labelAlamatField)
                    .addComponent(labelNimField)
                    .addComponent(judul_panel_daftar)
                    .addGroup(daftaPanelLayout.createSequentialGroup()
                        .addComponent(externalButton)
                        .addGap(30, 30, 30)
                        .addComponent(internalButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(profesionalButton))
                    .addComponent(daftarNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, daftaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(daftarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(276, 276, 276))
        );
        daftaPanelLayout.setVerticalGroup(
            daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftaPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(daftaPanelLayout.createSequentialGroup()
                        .addComponent(judul_panel_daftar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(daftaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(externalButton)
                            .addComponent(internalButon)
                            .addComponent(profesionalButton))
                        .addGap(25, 25, 25)
                        .addComponent(labelNamaField)
                        .addGap(18, 18, 18)
                        .addComponent(daftarNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(labelAlamatField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daftarAlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(labelNimField)
                        .addGap(4, 4, 4)
                        .addComponent(daftarNimField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelPasswordField))
                    .addComponent(logoDaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(daftarPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daftarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        login.add(daftaPanel, "daftarCard");

        app.add(login, "loginMenu");

        navbar.setBackground(new java.awt.Color(255, 255, 255));

        logoNavbar.setBackground(new java.awt.Color(255, 255, 255));
        logoNavbar.setFont(new java.awt.Font("Playfair Display", 0, 18)); // NOI18N
        logoNavbar.setForeground(new java.awt.Color(255, 153, 0));
        logoNavbar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo Sadhar1.png"))); // NOI18N
        logoNavbar.setText("SIA USD");

        textMenuUtama.setBackground(new java.awt.Color(255, 255, 255));
        textMenuUtama.setFont(new java.awt.Font("Playfair Display", 0, 16)); // NOI18N
        textMenuUtama.setText("MENU UTAMA");

        dashboardButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        dashboardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-dashboard.png"))); // NOI18N
        dashboardButton.setText(" Dashboard");
        dashboardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardButtonMouseClicked(evt);
            }
        });

        kelaskuButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        kelaskuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-kelasku.png"))); // NOI18N
        kelaskuButton.setText(" Kelasku");
        kelaskuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kelaskuButtonMouseClicked(evt);
            }
        });

        pesertaButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        pesertaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-peserta-kelas.png"))); // NOI18N
        pesertaButton.setText("Peserta Kelas");
        pesertaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesertaButtonMouseClicked(evt);
            }
        });

        keuanganButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        keuanganButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-keuangan.png"))); // NOI18N
        keuanganButton.setText(" Keuangan ");
        keuanganButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keuanganButtonMouseClicked(evt);
            }
        });

        textAkunSaya.setBackground(new java.awt.Color(255, 255, 255));
        textAkunSaya.setFont(new java.awt.Font("Playfair Display", 0, 18)); // NOI18N
        textAkunSaya.setText("Akun Saya");

        editProfileButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        editProfileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-profile.png"))); // NOI18N
        editProfileButton.setText("Edit Profile");
        editProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editProfileButtonMouseClicked(evt);
            }
        });

        logOutButton.setFont(new java.awt.Font("Playfair Display", 0, 14)); // NOI18N
        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-logout.png"))); // NOI18N
        logOutButton.setText("Log Out");
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout navbarLayout = new javax.swing.GroupLayout(navbar);
        navbar.setLayout(navbarLayout);
        navbarLayout.setHorizontalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoNavbar)
                    .addComponent(textAkunSaya)
                    .addComponent(textMenuUtama)
                    .addGroup(navbarLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keuanganButton)
                            .addComponent(pesertaButton)
                            .addComponent(editProfileButton)
                            .addComponent(logOutButton)
                            .addComponent(dashboardButton)
                            .addComponent(kelaskuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        navbarLayout.setVerticalGroup(
            navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoNavbar)
                .addGap(30, 30, 30)
                .addComponent(textMenuUtama)
                .addGap(30, 30, 30)
                .addComponent(dashboardButton)
                .addGap(18, 18, 18)
                .addComponent(kelaskuButton)
                .addGap(18, 18, 18)
                .addComponent(pesertaButton)
                .addGap(18, 18, 18)
                .addComponent(keuanganButton)
                .addGap(36, 36, 36)
                .addComponent(textAkunSaya)
                .addGap(18, 18, 18)
                .addComponent(editProfileButton)
                .addGap(18, 18, 18)
                .addComponent(logOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(204, 255, 51));
        content.setLayout(new java.awt.CardLayout());

        dashboard.setBackground(new java.awt.Color(255, 249, 186));

        selamatDatangPanel.setBackground(new java.awt.Color(255, 192, 140));

        logoSelamatDatang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-selamat-datang.png"))); // NOI18N

        textSelamatDatang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textSelamatDatang.setForeground(new java.awt.Color(255, 102, 51));
        textSelamatDatang.setText("SELAMAT DATANG");

        namaPeserta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        namaPeserta.setForeground(new java.awt.Color(255, 102, 51));
        namaPeserta.setText("FERLY");

        textTambahan1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textTambahan1.setForeground(new java.awt.Color(255, 102, 51));
        textTambahan1.setText("Anda Belum Memiliki Mata Kuliah Silahkan Ke Kelasku Untuk ");

        textTambahan2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textTambahan2.setForeground(new java.awt.Color(255, 102, 51));
        textTambahan2.setText("Memilih Mata Kuliah");

        javax.swing.GroupLayout selamatDatangPanelLayout = new javax.swing.GroupLayout(selamatDatangPanel);
        selamatDatangPanel.setLayout(selamatDatangPanelLayout);
        selamatDatangPanelLayout.setHorizontalGroup(
            selamatDatangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selamatDatangPanelLayout.createSequentialGroup()
                .addGroup(selamatDatangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selamatDatangPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(textSelamatDatang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPeserta))
                    .addGroup(selamatDatangPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(selamatDatangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTambahan2)
                            .addComponent(textTambahan1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(logoSelamatDatang)
                .addGap(43, 43, 43))
        );
        selamatDatangPanelLayout.setVerticalGroup(
            selamatDatangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selamatDatangPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoSelamatDatang, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
            .addGroup(selamatDatangPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(selamatDatangPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSelamatDatang)
                    .addComponent(namaPeserta))
                .addGap(11, 11, 11)
                .addComponent(textTambahan1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTambahan2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel15.setForeground(new java.awt.Color(255, 102, 51));
        jLabel15.setText("Belum Ada Kelas");

        javax.swing.GroupLayout dashboardLayout = new javax.swing.GroupLayout(dashboard);
        dashboard.setLayout(dashboardLayout);
        dashboardLayout.setHorizontalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(selamatDatangPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        dashboardLayout.setVerticalGroup(
            dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(selamatDatangPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
            .addGroup(dashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(dashboardLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        content.add(dashboard, "dashboardCard");

        dashboardAktif.setBackground(new java.awt.Color(246, 253, 255));

        selamatDatangPanel2.setBackground(new java.awt.Color(255, 192, 140));

        logoSelamatDatang1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-selamat-datang.png"))); // NOI18N

        textSelamatDatang1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textSelamatDatang1.setForeground(new java.awt.Color(255, 102, 51));
        textSelamatDatang1.setText("SELAMAT DATANG");

        namaPeserta1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        namaPeserta1.setForeground(new java.awt.Color(255, 102, 51));
        namaPeserta1.setText("FERLY");

        textTambahan3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textTambahan3.setForeground(new java.awt.Color(255, 102, 51));
        textTambahan3.setText("Anda Belum Memiliki Mata Kuliah Silahkan Ke Kelasku Untuk ");

        textTambahan4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textTambahan4.setForeground(new java.awt.Color(255, 102, 51));
        textTambahan4.setText("Memilih Mata Kuliah");

        javax.swing.GroupLayout selamatDatangPanel2Layout = new javax.swing.GroupLayout(selamatDatangPanel2);
        selamatDatangPanel2.setLayout(selamatDatangPanel2Layout);
        selamatDatangPanel2Layout.setHorizontalGroup(
            selamatDatangPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selamatDatangPanel2Layout.createSequentialGroup()
                .addGroup(selamatDatangPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(selamatDatangPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(textSelamatDatang1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaPeserta1))
                    .addGroup(selamatDatangPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(selamatDatangPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textTambahan4)
                            .addComponent(textTambahan3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(logoSelamatDatang1)
                .addGap(43, 43, 43))
        );
        selamatDatangPanel2Layout.setVerticalGroup(
            selamatDatangPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selamatDatangPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoSelamatDatang1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
            .addGroup(selamatDatangPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(selamatDatangPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textSelamatDatang1)
                    .addComponent(namaPeserta1))
                .addGap(11, 11, 11)
                .addComponent(textTambahan3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTambahan4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dashboardAktifLayout = new javax.swing.GroupLayout(dashboardAktif);
        dashboardAktif.setLayout(dashboardAktifLayout);
        dashboardAktifLayout.setHorizontalGroup(
            dashboardAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardAktifLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(selamatDatangPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        dashboardAktifLayout.setVerticalGroup(
            dashboardAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardAktifLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(selamatDatangPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );

        content.add(dashboardAktif, "dashboardAktifCard");

        kelasku.setBackground(new java.awt.Color(255, 249, 186));

        textKelasku.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textKelasku.setForeground(new java.awt.Color(255, 153, 51));
        textKelasku.setText("SILAHKAN PILIH KELAS");

        textMataKuliah1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textMataKuliah1.setText("Mata Kuliah 1");

        mataKuliahPilihan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih mata kuliah", "Pemograman Analisis Data", "INTERNET DAN APP", "STRUKTUR DATA NON LINEAR", "Algoritma Program" }));

        textMataKuliah2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textMataKuliah2.setText("Mata Kuliah 2");

        mataKuliahPilihan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih mata kuliah", "Pemograman Analisis Data", "INTERNET DAN APP", "STRUKTUR DATA NON LINEAR", "Algoritma Program" }));

        textMatakuliah3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        textMatakuliah3.setText("Mata Kuliah 3");

        mataKuliahPilihan3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pilih mata kuliah", "Pemograman Analisis Data", "INTERNET DAN APP", "STRUKTUR DATA NON LINEAR", "Algoritma Program" }));

        logoPanelKelasku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-daftar-kelas.png"))); // NOI18N

        tambahMatkulButton.setBackground(new java.awt.Color(255, 153, 0));
        tambahMatkulButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tambahMatkulButton.setForeground(new java.awt.Color(255, 255, 255));
        tambahMatkulButton.setText("Tambah Mata Kuliah");
        tambahMatkulButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahMatkulButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kelaskuLayout = new javax.swing.GroupLayout(kelasku);
        kelasku.setLayout(kelaskuLayout);
        kelaskuLayout.setHorizontalGroup(
            kelaskuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelaskuLayout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(textKelasku)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(kelaskuLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(kelaskuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kelaskuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textMatakuliah3)
                        .addComponent(textMataKuliah2)
                        .addComponent(textMataKuliah1)
                        .addComponent(mataKuliahPilihan2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mataKuliahPilihan3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mataKuliahPilihan1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(tambahMatkulButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(logoPanelKelasku)
                .addGap(46, 46, 46))
        );
        kelaskuLayout.setVerticalGroup(
            kelaskuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kelaskuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(textKelasku)
                .addGroup(kelaskuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(kelaskuLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(textMataKuliah1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mataKuliahPilihan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(textMataKuliah2)
                        .addGap(18, 18, 18)
                        .addComponent(mataKuliahPilihan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textMatakuliah3)
                        .addGap(18, 18, 18)
                        .addComponent(mataKuliahPilihan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tambahMatkulButton))
                    .addGroup(kelaskuLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(logoPanelKelasku)))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        content.add(kelasku, "kelaskuCard");

        javax.swing.GroupLayout kelaskuAktifLayout = new javax.swing.GroupLayout(kelaskuAktif);
        kelaskuAktif.setLayout(kelaskuAktifLayout);
        kelaskuAktifLayout.setHorizontalGroup(
            kelaskuAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        kelaskuAktifLayout.setVerticalGroup(
            kelaskuAktifLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        content.add(kelaskuAktif, "card5");

        pesertaKelas.setBackground(new java.awt.Color(255, 249, 186));

        labelMataKuliah1.setForeground(new java.awt.Color(255, 102, 51));
        labelMataKuliah1.setText("MATA KULIAH");

        mataKuliah1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mataKuliah1.setForeground(new java.awt.Color(255, 102, 51));
        mataKuliah1.setText("Algoritma Program");

        tabelPesertaMatkul1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "TIPE MAHASISWA"
            }
        ));
        jScrollPane1.setViewportView(tabelPesertaMatkul1);

        labelMataKuliah2.setForeground(new java.awt.Color(255, 102, 51));
        labelMataKuliah2.setText("MATA KULIAH");

        tabelPesertaMatkul2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "TIPE MAHASISWA"
            }
        ));
        jScrollPane2.setViewportView(tabelPesertaMatkul2);

        labelMataKuliah3.setForeground(new java.awt.Color(255, 102, 51));
        labelMataKuliah3.setText("MATA KULIAH");

        tabelPesertaMatkul3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "TIPE MAHASISWA"
            }
        ));
        jScrollPane3.setViewportView(tabelPesertaMatkul3);

        mataKuliah2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mataKuliah2.setForeground(new java.awt.Color(255, 102, 51));
        mataKuliah2.setText("Pemrograman Analisis Data");

        mataKuliah3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mataKuliah3.setForeground(new java.awt.Color(255, 102, 51));
        mataKuliah3.setText("Internet Dan App");

        javax.swing.GroupLayout pesertaKelasLayout = new javax.swing.GroupLayout(pesertaKelas);
        pesertaKelas.setLayout(pesertaKelasLayout);
        pesertaKelasLayout.setHorizontalGroup(
            pesertaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesertaKelasLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(pesertaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pesertaKelasLayout.createSequentialGroup()
                        .addComponent(labelMataKuliah3)
                        .addGap(18, 18, 18)
                        .addComponent(mataKuliah3))
                    .addGroup(pesertaKelasLayout.createSequentialGroup()
                        .addComponent(labelMataKuliah2)
                        .addGap(18, 18, 18)
                        .addComponent(mataKuliah2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pesertaKelasLayout.createSequentialGroup()
                        .addComponent(labelMataKuliah1)
                        .addGap(18, 18, 18)
                        .addComponent(mataKuliah1)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        pesertaKelasLayout.setVerticalGroup(
            pesertaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pesertaKelasLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pesertaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMataKuliah1)
                    .addComponent(mataKuliah1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(pesertaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMataKuliah2)
                    .addComponent(mataKuliah2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(pesertaKelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMataKuliah3)
                    .addComponent(mataKuliah3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        content.add(pesertaKelas, "pesertaCard");

        transaksi.setBackground(new java.awt.Color(255, 249, 186));

        panelInfoPeserta.setBackground(new java.awt.Color(255, 192, 140));

        logoSelamatDatang2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-selamat-datang.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 66, 15));
        jLabel8.setText("NAMA MAHASISWA    : ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 66, 15));
        jLabel9.setText("NIM                               :");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 66, 15));
        jLabel10.setText("PRODI                           :");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 51));
        jLabel11.setText("FERLY");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 51));
        jLabel12.setText("225314105");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 102, 51));
        jLabel13.setText("INFORMATIKA");

        javax.swing.GroupLayout panelInfoPesertaLayout = new javax.swing.GroupLayout(panelInfoPeserta);
        panelInfoPeserta.setLayout(panelInfoPesertaLayout);
        panelInfoPesertaLayout.setHorizontalGroup(
            panelInfoPesertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoPesertaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelInfoPesertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(panelInfoPesertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 284, Short.MAX_VALUE)
                .addComponent(logoSelamatDatang2)
                .addGap(43, 43, 43))
        );
        panelInfoPesertaLayout.setVerticalGroup(
            panelInfoPesertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPesertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoSelamatDatang2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
            .addGroup(panelInfoPesertaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelInfoPesertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoPesertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInfoPesertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Kode Matkul", "Nama Matkul", "Biaya"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelTransaksi);
        if (tabelTransaksi.getColumnModel().getColumnCount() > 0) {
            tabelTransaksi.getColumnModel().getColumn(0).setResizable(false);
            tabelTransaksi.getColumnModel().getColumn(1).setResizable(false);
            tabelTransaksi.getColumnModel().getColumn(2).setResizable(false);
        }

        bayarButton.setBackground(new java.awt.Color(254, 115, 93));
        bayarButton.setForeground(new java.awt.Color(255, 255, 255));
        bayarButton.setText("BAYAR");
        bayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addComponent(panelInfoPeserta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(transaksiLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addComponent(bayarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transaksiLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelInfoPeserta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(bayarButton)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        content.add(transaksi, "transaksiCard");

        editProfile.setBackground(new java.awt.Color(255, 249, 186));

        logoEditProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo-edit-profile.png"))); // NOI18N

        labelNamaField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNamaField1.setForeground(new java.awt.Color(254, 115, 93));
        labelNamaField1.setText("Nama Lengkap");

        ubahNamaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubahNamaFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubahNamaFieldFocusLost(evt);
            }
        });
        ubahNamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahNamaFieldActionPerformed(evt);
            }
        });

        labelAlamatField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAlamatField1.setForeground(new java.awt.Color(254, 115, 93));
        labelAlamatField1.setText("Alamat");

        ubahAlamatField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubahAlamatFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubahAlamatFieldFocusLost(evt);
            }
        });
        ubahAlamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahAlamatFieldActionPerformed(evt);
            }
        });

        labelNimField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelNimField1.setForeground(new java.awt.Color(254, 115, 93));
        labelNimField1.setText("Nim");

        ubahNimField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubahNimFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubahNimFieldFocusLost(evt);
            }
        });
        ubahNimField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahNimFieldActionPerformed(evt);
            }
        });

        labelPasswordField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelPasswordField1.setForeground(new java.awt.Color(254, 115, 93));
        labelPasswordField1.setText("Password");

        ubahPasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubahPasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubahPasswordFieldFocusLost(evt);
            }
        });
        ubahPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahPasswordFieldActionPerformed(evt);
            }
        });

        ubahButton.setBackground(new java.awt.Color(254, 115, 93));
        ubahButton.setForeground(new java.awt.Color(255, 255, 255));
        ubahButton.setText("UBAH");
        ubahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout editProfileLayout = new javax.swing.GroupLayout(editProfile);
        editProfile.setLayout(editProfileLayout);
        editProfileLayout.setHorizontalGroup(
            editProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editProfileLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoEditProfile)
                .addGroup(editProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProfileLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(editProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPasswordField1)
                            .addGroup(editProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelNimField1)
                                .addComponent(labelNamaField1)
                                .addComponent(ubahNamaField, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                .addComponent(labelAlamatField1)
                                .addComponent(ubahAlamatField)
                                .addComponent(ubahNimField))
                            .addComponent(ubahPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(editProfileLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(ubahButton)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        editProfileLayout.setVerticalGroup(
            editProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editProfileLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(editProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(editProfileLayout.createSequentialGroup()
                        .addComponent(labelNamaField1)
                        .addGap(26, 26, 26)
                        .addComponent(ubahNamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(labelAlamatField1)
                        .addGap(18, 18, 18)
                        .addComponent(ubahAlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelNimField1)
                        .addGap(18, 18, 18)
                        .addComponent(ubahNimField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPasswordField1)
                        .addGap(18, 18, 18)
                        .addComponent(ubahPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ubahButton))
                    .addComponent(logoEditProfile))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        content.add(editProfile, "editProfileCard");

        javax.swing.GroupLayout bodyLayout = new javax.swing.GroupLayout(body);
        body.setLayout(bodyLayout);
        bodyLayout.setHorizontalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyLayout.createSequentialGroup()
                .addComponent(navbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodyLayout.setVerticalGroup(
            bodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        app.add(body, "mainMenu");

        getContentPane().add(app, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nimFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
      cardLogin.show(login, "daftarCard");
    }//GEN-LAST:event_jLabel7MouseClicked

    private void daftarNimFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarNimFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarNimFieldActionPerformed

    private void daftarNamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarNamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarNamaFieldActionPerformed

    private void daftarAlamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarAlamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarAlamatFieldActionPerformed

    private void daftar_nama_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void daftarAlamatFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarAlamatFieldFocusGained
        Color warna_utama = new Color(254,115,93);
        daftarAlamatField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_daftarAlamatFieldFocusGained

    private void daftarAlamatFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarAlamatFieldFocusLost
        Color warna_default = new Color(184,207,229);
        daftarAlamatField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_daftarAlamatFieldFocusLost

    private void daftarPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daftarPasswordFieldActionPerformed

    private void internalButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_internalButonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_internalButonActionPerformed

    private void externalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_externalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_externalButtonActionPerformed

    private void profesionalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesionalButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesionalButtonActionPerformed

    private void daftarNamaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarNamaFieldFocusGained

          daftarNamaField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_daftarNamaFieldFocusGained

    private void daftarNamaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarNamaFieldFocusLost

        daftarNamaField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_daftarNamaFieldFocusLost

    private void daftarNimFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarNimFieldFocusGained
        
        daftarNimField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_daftarNimFieldFocusGained

    private void daftarPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarPasswordFieldFocusGained
         daftarPasswordField.setBorder(new LineBorder(warna_utama,2));
       
    }//GEN-LAST:event_daftarPasswordFieldFocusGained

    private void daftarNimFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarNimFieldFocusLost
        daftarNimField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_daftarNimFieldFocusLost

    private void daftarPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_daftarPasswordFieldFocusLost
        daftarPasswordField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_daftarPasswordFieldFocusLost

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        cardBody.show(app, "mainMenu");
        cardContent.show(content, "dashboardCard");
        /* if (nimField.getText().equals("") && passwordField.getText().equals("")) {
            alertNotif.setForeground(Color.red);
        } else {
            alertNotif.setForeground(Color.blue);
            cardBody.show(app, "mainMenu");
            cardContent.show(content, "dashboardContent");
        }
        */
    }//GEN-LAST:event_loginButtonActionPerformed

    private void tambahMatkulButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahMatkulButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tambahMatkulButtonActionPerformed

    private void kelaskuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kelaskuButtonMouseClicked
         cardContent.show(content, "kelaskuCard");
    }//GEN-LAST:event_kelaskuButtonMouseClicked

    private void dashboardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardButtonMouseClicked
        cardContent.show(content, "dashboardCard");
    }//GEN-LAST:event_dashboardButtonMouseClicked

    private void pesertaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesertaButtonMouseClicked
        cardContent.show(content, "pesertaCard");
    }//GEN-LAST:event_pesertaButtonMouseClicked

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        cardBody.show(app, "loginMenu");
        cardLogin.show(login, "LoginCard");
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void keuanganButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keuanganButtonMouseClicked
         cardContent.show(content, "transaksiCard");
    }//GEN-LAST:event_keuanganButtonMouseClicked

    private void bayarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarButtonActionPerformed

    private void ubahNamaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubahNamaFieldFocusGained
        ubahNamaField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_ubahNamaFieldFocusGained

    private void ubahNamaFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubahNamaFieldFocusLost
         ubahNamaField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_ubahNamaFieldFocusLost

    private void ubahNamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahNamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahNamaFieldActionPerformed

    private void ubahAlamatFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubahAlamatFieldFocusGained
         ubahAlamatField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_ubahAlamatFieldFocusGained

    private void ubahAlamatFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubahAlamatFieldFocusLost
         ubahAlamatField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_ubahAlamatFieldFocusLost

    private void ubahAlamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahAlamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahAlamatFieldActionPerformed

    private void ubahNimFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubahNimFieldFocusGained
         ubahNimField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_ubahNimFieldFocusGained

    private void ubahNimFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubahNimFieldFocusLost
        ubahNimField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_ubahNimFieldFocusLost

    private void ubahNimFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahNimFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahNimFieldActionPerformed

    private void ubahPasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubahPasswordFieldFocusGained
        ubahPasswordField.setBorder(new LineBorder(warna_utama,2));
    }//GEN-LAST:event_ubahPasswordFieldFocusGained

    private void ubahPasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubahPasswordFieldFocusLost
        ubahPasswordField.setBorder(new LineBorder(warna_default,2));
    }//GEN-LAST:event_ubahPasswordFieldFocusLost

    private void ubahPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahPasswordFieldActionPerformed

    private void ubahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ubahButtonActionPerformed

    private void editProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editProfileButtonMouseClicked
         cardContent.show(content, "editProfileCard");
    }//GEN-LAST:event_editProfileButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertNotif;
    private javax.swing.JPanel app;
    private javax.swing.JButton bayarButton;
    private javax.swing.JPanel body;
    private javax.swing.JPanel content;
    private javax.swing.JPanel daftaPanel;
    private javax.swing.JTextField daftarAlamatField;
    private javax.swing.JButton daftarButton;
    private javax.swing.JTextField daftarNamaField;
    private javax.swing.JTextField daftarNimField;
    private javax.swing.JTextField daftarPasswordField;
    private javax.swing.JPanel dashboard;
    private javax.swing.JPanel dashboardAktif;
    private javax.swing.JLabel dashboardButton;
    private javax.swing.JPanel editProfile;
    private javax.swing.JLabel editProfileButton;
    private javax.swing.JRadioButton externalButton;
    private javax.swing.ButtonGroup groupTipeMahasiswa;
    private javax.swing.JRadioButton internalButon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel judul_panel_daftar;
    private javax.swing.JPanel kelasku;
    private javax.swing.JPanel kelaskuAktif;
    private javax.swing.JLabel kelaskuButton;
    private javax.swing.JLabel keuanganButton;
    private javax.swing.JLabel labelAlamatField;
    private javax.swing.JLabel labelAlamatField1;
    private javax.swing.JLabel labelMataKuliah1;
    private javax.swing.JLabel labelMataKuliah2;
    private javax.swing.JLabel labelMataKuliah3;
    private javax.swing.JLabel labelNamaField;
    private javax.swing.JLabel labelNamaField1;
    private javax.swing.JLabel labelNimField;
    private javax.swing.JLabel labelNimField1;
    private javax.swing.JLabel labelPasswordField;
    private javax.swing.JLabel labelPasswordField1;
    private javax.swing.JLabel logOutButton;
    private javax.swing.JPanel login;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logoDaftar;
    private javax.swing.JLabel logoEditProfile;
    private javax.swing.JLabel logoLogin;
    private javax.swing.JLabel logoNavbar;
    private javax.swing.JLabel logoNim;
    private javax.swing.JLabel logoPanelKelasku;
    private javax.swing.JLabel logoSelamatDatang;
    private javax.swing.JLabel logoSelamatDatang1;
    private javax.swing.JLabel logoSelamatDatang2;
    private javax.swing.JLabel logoUser;
    private javax.swing.JLabel mataKuliah1;
    private javax.swing.JLabel mataKuliah2;
    private javax.swing.JLabel mataKuliah3;
    private javax.swing.JComboBox<String> mataKuliahPilihan1;
    private javax.swing.JComboBox<String> mataKuliahPilihan2;
    private javax.swing.JComboBox<String> mataKuliahPilihan3;
    private javax.swing.JLabel namaPeserta;
    private javax.swing.JLabel namaPeserta1;
    private javax.swing.JPanel navbar;
    private javax.swing.JTextField nimField;
    private javax.swing.JPanel nimPanelField;
    private javax.swing.JPanel panelDaftar;
    private javax.swing.JPanel panelInfoPeserta;
    private javax.swing.JTextField passwordField;
    private javax.swing.JPanel passwordPanelField;
    private javax.swing.JLabel pesertaButton;
    private javax.swing.JPanel pesertaKelas;
    private javax.swing.JRadioButton profesionalButton;
    private javax.swing.JPanel selamatDatangPanel;
    private javax.swing.JPanel selamatDatangPanel2;
    private javax.swing.JTable tabelPesertaMatkul1;
    private javax.swing.JTable tabelPesertaMatkul2;
    private javax.swing.JTable tabelPesertaMatkul3;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton tambahMatkulButton;
    private javax.swing.JLabel textAkunSaya;
    private javax.swing.JLabel textKelasku;
    private javax.swing.JLabel textMataKuliah1;
    private javax.swing.JLabel textMataKuliah2;
    private javax.swing.JLabel textMatakuliah3;
    private javax.swing.JLabel textMenuUtama;
    private javax.swing.JLabel textSelamatDatang;
    private javax.swing.JLabel textSelamatDatang1;
    private javax.swing.JLabel textTambahan1;
    private javax.swing.JLabel textTambahan2;
    private javax.swing.JLabel textTambahan3;
    private javax.swing.JLabel textTambahan4;
    private javax.swing.JPanel transaksi;
    private javax.swing.JTextField ubahAlamatField;
    private javax.swing.JButton ubahButton;
    private javax.swing.JTextField ubahNamaField;
    private javax.swing.JTextField ubahNimField;
    private javax.swing.JTextField ubahPasswordField;
    // End of variables declaration//GEN-END:variables
}
